"""Adicionando coluna categoria em Usuario

Revision ID: 09a0d7154956
Revises: 150f0b5195a5
Create Date: 2025-10-29 09:50:41.688320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09a0d7154956'
down_revision = '150f0b5195a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###
