"""Adicionando campos de revisão, inspeção e lugares ao Carro

Revision ID: 150f0b5195a5
Revises: 
Create Date: 2025-10-21 10:23:16.803964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150f0b5195a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserva')
    with op.batch_alter_table('aluguel', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('forma_pagamento',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('telefone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('cpf',
               existing_type=sa.TEXT(),
               type_=sa.String(length=15),
               existing_nullable=False)
        batch_op.alter_column('cep',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_ultima_revisao', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('data_proxima_revisao', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('data_ultima_inspecao', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('quantidade_lugares', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.drop_column('quantidade_lugares')
        batch_op.drop_column('data_ultima_inspecao')
        batch_op.drop_column('data_proxima_revisao')
        batch_op.drop_column('data_ultima_revisao')

    with op.batch_alter_table('aluguel', schema=None) as batch_op:
        batch_op.alter_column('cep',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('cpf',
               existing_type=sa.String(length=15),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('telefone',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('forma_pagamento',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('reserva',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('aluguel_id', sa.INTEGER(), nullable=False),
    sa.Column('nova_data_inicio', sa.DATE(), nullable=False),
    sa.Column('nova_data_fim', sa.DATE(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['aluguel_id'], ['aluguel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
