"""Adicionando coluna categoria em Veiculo

Revision ID: 4087d9d0fc98
Revises: 8e50191ffba3
Create Date: 2025-11-05 09:41:28.048695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4087d9d0fc98'
down_revision = '8e50191ffba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veiculo', schema=None) as batch_op:
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###
